src/store2/Controllers/BranchesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using store2.Models;

namespace store2.Controllers
{
    public class BranchesController : Controller
    {
        private ApplicationDbContext _context;

        public BranchesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Branches
        public IActionResult Index()
        {
            return View(_context.Branch.ToList());
        }

        // GET: Branches/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Branch branch = _context.Branch.Single(m => m.ID == id);
            if (branch == null)
            {
                return HttpNotFound();
            }

            return View(branch);
        }

        // GET: Branches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Branch branch)
        {
            if (ModelState.IsValid)
            {
                _context.Branch.Add(branch);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        // GET: Branches/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Branch branch = _context.Branch.Single(m => m.ID == id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Branch branch)
        {
            if (ModelState.IsValid)
            {
                _context.Update(branch);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        // GET: Branches/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Branch branch = _context.Branch.Single(m => m.ID == id);
            if (branch == null)
            {
                return HttpNotFound();
            }

            return View(branch);
        }

        // POST: Branches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Branch branch = _context.Branch.Single(m => m.ID == id);
            _context.Branch.Remove(branch);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult getAddresses()
        {
            var address = _context.Branch.Select(branch => branch.Address);

            return Json(address);
        }





    }
}

src/store2/Controllers/ItemsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using store2.Models;
using System;
using System.Collections.Generic;

namespace store2.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext _context;
        
        public ItemsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Items
        public IActionResult Men(string Names, string SearchDetails, int MaxPrice, DateTime FromDate , DateTime EndDate ,string supplierSearch)
        {
            //List<Supplier> SupplierL = new List<Supplier>();
            //List<Item> ItemL = new List<Item>();

            var NameList = new List<string>();

            var q = from n in _context.Item where n.Category == "Men" select n.Name;
            NameList.AddRange(q.Distinct());
            ViewBag.Names = new SelectList(NameList);

            var SuppList = new List<string>();
            var a = from n in _context.Supplier select n.Name;
            SuppList.AddRange(a.Distinct());
            ViewBag.Suppliers = new SelectList(SuppList);

            var Items = from i in _context.Item select i;

            if (!String.IsNullOrEmpty(Names))
            {
                Items = Items.Where(s => s.Name == Names);
            }
            if (!String.IsNullOrEmpty(SearchDetails))
            {
                Items = Items.Where(d => d.Details.Contains(SearchDetails));
            }
            if (MaxPrice > 0)
            {
                Items = Items.Where(p => p.Price < MaxPrice);
            }
            if (FromDate != DateTime.MinValue)
            {
                Items = Items.Where(p => p.DateOfPublish >= FromDate );
            }
            if (EndDate != DateTime.MinValue)
            {
                Items = Items.Where(p => p.DateOfPublish <= EndDate);
            }


            //List<object> ListI = new List<object>();
            //ListI.Add(list.ToList());

            var applicationDbContext = _context.Item.Include(i => i.Supplier);
            return View(Items);
        }

        public IActionResult Women(string Names, string SearchDetails, int MaxPrice, DateTime FromDate, DateTime EndDate)
        {
            var NameList = new List<string>();

            var q = from n in _context.Item where n.Category == "Women" select n.Name;
            NameList.AddRange(q.Distinct());
            ViewBag.Names = new SelectList(NameList);

            var SuppList = new List<string>();
            var a = from n in _context.Supplier select n.Name;
            SuppList.AddRange(a.Distinct());
            ViewBag.Suppliers = new SelectList(SuppList);

            var Items = from i in _context.Item select i;

            if (!String.IsNullOrEmpty(Names))
            {
                Items = Items.Where(s => s.Name == Names);
            }
            if (!String.IsNullOrEmpty(SearchDetails))
            {
                Items = Items.Where(d => d.Details.Contains(SearchDetails));
            }
            if (MaxPrice > 0)
            {
                Items = Items.Where(p => p.Price < MaxPrice);
            }
            if (FromDate != DateTime.MinValue)
            {
                Items = Items.Where(p => p.DateOfPublish >= FromDate);
            }
            if (EndDate != DateTime.MinValue)
            {
                Items = Items.Where(p => p.DateOfPublish <= EndDate);
            }
            var applicationDbContext = _context.Item.Include(i => i.Supplier);
            return View(Items);
        }
        public IActionResult Children(string Names, string SearchDetails, int MaxPrice, DateTime FromDate, DateTime EndDate)
        {
            var NameList = new List<string>();

            var q = from n in _context.Item where n.Category == "Children" select n.Name;
            NameList.AddRange(q.Distinct());
            ViewBag.Names = new SelectList(NameList);

            var SuppList = new List<string>();
            var a = from n in _context.Supplier select n.Name;
            SuppList.AddRange(a.Distinct());
            ViewBag.Suppliers = new SelectList(SuppList);

            var Items = from i in _context.Item select i;

            if (!String.IsNullOrEmpty(Names))
            {
                Items = Items.Where(s => s.Name == Names);
            }
            if (!String.IsNullOrEmpty(SearchDetails))
            {
                Items = Items.Where(d => d.Details.Contains(SearchDetails));
            }
            if (MaxPrice > 0)
            {
                Items = Items.Where(p => p.Price < MaxPrice);
            }
            if (FromDate != DateTime.MinValue)
            {
                Items = Items.Where(p => p.DateOfPublish >= FromDate);
            }
            if (EndDate != DateTime.MinValue)
            {
                Items = Items.Where(p => p.DateOfPublish <= EndDate);
            }
            var applicationDbContext = _context.Item.Include(i => i.Supplier);
            return View(Items);
        }
        public IActionResult PageItem(int ID)
        {

            var Item = from i in _context.Item select i;

            Item = Item.Where(p => p.ID == ID);
            
            var applicationDbContext = _context.Item.Include(i => i.Supplier);
            return View(Item);
        }


        // GET: Items/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Item item = _context.Item.Single(m => m.ID == id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create(string Suppliers,string Categories)
        {
            var CategoryList = new List<string>();
            var q = from c in _context.Item select c.Category;
            CategoryList.AddRange(q.Distinct());
            ViewBag.Categories = new SelectList(CategoryList);

            var SupplierList = new List<string>();
            var query = from s in _context.Supplier select s.Name;
            SupplierList.AddRange(query.Distinct());
            ViewBag.Suppliers = new SelectList(SupplierList);
            
            ViewData["SupplierID"] = new SelectList(_context.Set<Supplier>(), "ID", "Supplier");
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item item , string Suppliers, string Categories)
        {
            Supplier sup = _context.Supplier.Where(d => d.Name == Suppliers).Single();
            item.Supplier = sup;
            if (ModelState.IsValid)
            {
                item.DateOfPublish = DateTime.Now;
                item.Category = Categories;
                item.Supplier.Name = Suppliers;
                _context.Item.Add(item);
                _context.SaveChanges();
                return RedirectToAction("Men");
            }

            ViewData["SupplierID"] = new SelectList(_context.Set<Supplier>(), "ID", "Supplier", item.SupplierID);
            return View(item);
        }

        // GET: Items/Edit/5
        public IActionResult Edit(int? id, string Suppliers,string Categories)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Item item = _context.Item.Single(m => m.ID == id);
            if (item == null)
            {
                return HttpNotFound();
            }

            var CategoryList = new List<string>();
            var q = from c in _context.Item select c.Category;
            CategoryList.AddRange(q.Distinct());
            ViewBag.Categories = new SelectList(CategoryList);

            var SupplierList = new List<string>();
            var query = from s in _context.Supplier select s.Name;
            SupplierList.AddRange(query.Distinct());
            ViewBag.Suppliers = new SelectList(SupplierList);

            ViewData["SupplierID"] = new SelectList(_context.Set<Supplier>(), "ID", "Supplier");
            return View(item);
        }

        // POST: Items/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Item item, string Suppliers, string Categories)
        {
            Supplier sup = _context.Supplier.Where(d => d.Name == Suppliers).Single();
            item.Supplier = sup;
            if (ModelState.IsValid)
            {
                item.Category = Categories;
                item.Supplier.Name = Suppliers;
                _context.Update(item);
                _context.SaveChanges();
                return RedirectToAction("Men");
            }
            ViewData["SupplierID"] = new SelectList(_context.Set<Supplier>(), "ID", "Supplier", item.SupplierID);
            return View(item);
        }

        // GET: Items/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Item item = _context.Item.Single(m => m.ID == id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Item item = _context.Item.Single(m => m.ID == id);
            _context.Item.Remove(item);
            _context.SaveChanges();
            return RedirectToAction("Men");
        }
    }
}

src/store2/Controllers/SuppliersController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using store2.Models;
using System.Collections.Generic;

namespace store2.Controllers
{
    public class SuppliersController : Controller
    {
        private ApplicationDbContext _context;

        public SuppliersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Suppliers
        public IActionResult Index()
        {
            List<object> list = new List<object>();
            list.Add(_context.Item.ToList());
            list.Add(_context.Supplier.ToList());
            return View(list);
        }

        // GET: Suppliers/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Supplier supplier = _context.Supplier.Single(m => m.ID == id);
            if (supplier == null)
            {
                return HttpNotFound();
            }

            return View(supplier);
        }

        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Supplier.Add(supplier);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Supplier supplier = _context.Supplier.Single(m => m.ID == id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Update(supplier);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Supplier supplier = _context.Supplier.Single(m => m.ID == id);
            if (supplier == null)
            {
                return HttpNotFound();
            }

            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = _context.Supplier.Single(m => m.ID == id);
            _context.Supplier.Remove(supplier);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/store2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
        <script src="~/js/d3pie.min.js" charset="utf-8"></script>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - store2</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
        @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">LiMa ZiKo</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @*<li><a asp-controller="Home" asp-action="Index">Home</a></li>*@
                        <li><a asp-controller="Items" asp-action="Men">Homens</a></li>
                        <li><a asp-controller="Items" asp-action="Women">Mulheres</a></li>
                        <li><a asp-controller="Items" asp-action="Children">Criancas</a></li>
                        <li><a asp-controller="Home" asp-action="About">Sobre</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contato</a></li>
                        <li><a asp-controller="Branches" asp-action="Index">Filiais</a></li>
                       
                        @if (User.IsInRole("admin"))
                        {
                            <li><a asp-controller="Suppliers" asp-action="Index">Fornecedores</a></li>
                        }
                        <li><a asp-controller="Home" asp-action="Static">Estatística</a></li>
                        
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            <content>
                @RenderBody()
                <hr />
            </content>
            
            <footer>
                <p>&copy; 2016 - store2</p>
                <div class="logos">
                    <a href="https://www.facebook.com/LiMa-ZiKo-1204641122879894/" target="_blank"><img src="~/images/facebook-logo.png" width="25" height="25" alt="Facebook" /></a>
                    <a href="https://www.youtube.com/" target="_blank"><img src="~/images/youtube-logo.png" width="25" height="25" alt="Facebook" /></a>
                    <a href="https://twitter.com/assos_com" target="_blank"><img src="~/images/twitter.png" width="25" height="25" alt="Facebook" /></a>
                </div>
                <div class="clear"></div>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>